version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  
  anchor_notes:
    build:
      network: host
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:mypass@postgres:5432/postgres
    ports:
      - "3000:3000"